version: "3.9"  # optional since v1.27.0
services:
  frontend:
    image: ghcr.io/crashzky/skillactive:latest
  server:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    links:
      - frontend